# Generated by Django 5.1.1 on 2024-09-24 06:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Patients",
            new_name="Patient",
        ),
    ]
