# Generated by Django 5.1.1 on 2024-09-24 12:44

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_alter_assessment_assessment_data_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_two",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="patients.question"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="assessment_data",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 24, 12, 44, 3, 415231, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
