# Generated by Django 5.1.1 on 2024-09-25 05:57

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_remove_assessment_assessment_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=30, region=None, unique=True
            ),
        ),
    ]
