# Generated by Django 5.1.1 on 2024-09-25 13:25

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0008_remove_question_assessment_assessment_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="final_score",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("1.0")),
                    django.core.validators.MaxValueValidator(Decimal("10.0")),
                ],
            ),
        ),
    ]
